capabilities:
  rest:
    readerClass: com.hltech.contracts.judged.publisher.capabilities.SwaggerCapabilitiesReader
    config:
      swaggerLocation: ./target/classes/static/swagger/
expectations:
  rest:
    readerClass: com.hltech.contracts.judged.publisher.expectations.PactExpectationsReader
    config:
      pactsLocation: ./target/pacts
