capabilities:
  - interface: rest
    readerClass: SwaggerCapabilitiesReader
    config:
      swaggerLocation: ./target/classes/static/swagger/
expectations:
  - interface: rest
    readerClass: PactExpectationsReader
    config:
      pactsLocation: ./target/pacts
